In [1]:
import numpy as np
import tensorflow as tf

np.random.seed(42)
tf.random.set_seed(42)

print("TF Version: ", tf.__version__)

TF Version:  2.20.0


In [2]:
# Let's make our first Tensors
# Tensors are a container for numbers, basically an N-Dimensional Array

scalar = tf.constant(7)
vector = tf.constant([1, 2, 3])
matrix = tf.constant([
    [1, 2],
    [3, 4],
    [5, 6]
])

# Let's get bigger
# Image batch of images that are 28x28, with 1 color channel, we have 10
image_batch = tf.zeros(shape=(10, 28, 28, 1))

examples = {
    "scalar": scalar,
    "vector": vector,
    "matrix": matrix,
    "image_batch": image_batch
}

for name, tensor in examples.items():
  print(name)
  print("     value/preview:", tensor)
  print("     shape", tensor.shape)
  print("     dtype:", tensor.dtype)
  print("     rank:", len(tensor.shape))
  print()

scalar
     value/preview: tf.Tensor(7, shape=(), dtype=int32)
     shape ()
     dtype: <dtype: 'int32'>
     rank: 0

vector
     value/preview: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
     shape (3,)
     dtype: <dtype: 'int32'>
     rank: 1

matrix
     value/preview: tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
     shape (3, 2)
     dtype: <dtype: 'int32'>
     rank: 2

image_batch
     value/preview: tf.Tensor(
[[[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ..

In [5]:
# Reminder Tensors are just containers for number
# We can do some math on these
# Some operations are element by element
# Other things like matrix multipulcation combines rows and columns

a = tf.constant([1,2,3])
b = tf.constant([10,20,30])
print(a+b)
print(a*b)
print(tf.square(a))

#2x3 Matrix
matrix_a = tf.constant([
    [1, 2, 3],
    [3, 4, 5],
])

# 3x1 Matrix
matrix_b = tf.constant([
    [7],
    [8],
    [9]
])

# Matrix multipulcation depends on the rows and columns and the order (i.e a*b
# doesn't always equal b*a). The columns of the first matrix need to match
# the rows of the second (j x k matrix time k x n matrix results in a j x n matrix)

print("Matrix Multipulcation")
# 2x3 * 3x1 -> 2x1 Matrix
print(tf.matmul(matrix_a, matrix_b))

tf.Tensor([11 22 33], shape=(3,), dtype=int32)
tf.Tensor([10 40 90], shape=(3,), dtype=int32)
tf.Tensor([1 4 9], shape=(3,), dtype=int32)
Matrix Multipulcation
tf.Tensor(
[[50]
 [98]], shape=(2, 1), dtype=int32)


In [10]:
# Reductions take values and reduce them into fewer values
# Basically we can before operations on tensors quickly and reduce them to a
# single value (we can also reduce on axes)

scores = tf.constant([
    [80, 90, 100],
    [70, 75, 85],
    [99, 92, 96]
])

# Let's take some common reductions
#Sum
sum = tf.reduce_sum(scores).numpy()
print(sum)

mean = tf.reduce_mean(scores).numpy()
max = tf.reduce_max(scores).numpy()
min = tf.reduce_min(scores).numpy()

print(mean, max, min)

# axis = 0 means reduce down the rows column by column
print(tf.reduce_mean(scores, axis=0).numpy())

# Reduces across columns row by row (deletes the axis it reduced)
print(tf.reduce_mean(scores, axis=1).numpy())

787
87 100 70
[83 85 93]
[90 76 95]
